name: "Update defaults in index"

on:
  workflow_dispatch:
    inputs:
      default:
        type: choice
        description: Default category to set
        options: 
          - hfz
          - divegrass
          - etc

concurrency:
  group: "update"
  cancel-in-progress: false

jobs:
  update-defaults:
    permissions:
      contents: write 
    name: "Update index.json automatically"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: runs local action to check updated files
        id: updater
        uses: betting-iscringe/updaterAction/defaults@main
        with:
          default: ${{ inputs.default }} 
      - name: stage changed files
        run: git add .
        if: steps.updater.outputs.hasUpdates
      - run: git config user.name github-actions-bot
        if: steps.updater.outputs.hasUpdates
      - run: git config user.email support+actions@github.com
        if: steps.updater.outputs.hasUpdates
      - name: commit changed files
        run: "git commit -m 'Updated: default event to ${{ inputs.default }}'"
        if: steps.updater.outputs.hasUpdates
      - name: fetch from master
        run: git fetch origin master
        if: steps.updater.outputs.hasUpdates
      - name: push code to master
        run: git push origin HEAD:master
        if: steps.updater.outputs.hasUpdates
